// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fywekrtawjtycfifezqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5d2VrcnRhd2p0eWNmaWZlenF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwOTI5MDYsImV4cCI6MjA1OTY2ODkwNn0.GaeN16xMVl0DdDtgTbIRatMTYP4r5xO2YTO51Hc4AFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);